### ISSUE TITLE
Deleting Annotation Points; Linking annotation points to Region/Genet

### ISSUE THREAD

**Issue by esme3093** [Jordan-Pierce/CoralNet-Toolbox#69]
Hello! 

I'm interested in using the self-annotation point tool to annotate and track areas around coral colonies. As of right now, I manually click where I'd like to add a point, but not able to delete any, if let's say I made a mistake. Could this be an option in the near future? 
I was also wondering if it's possible to link the annotated points to a Region or Genet ID by somehow selecting all the points and Region together and pressing the space bar or something similar? I tried selecting all the points and adding an attribute (in this case a coral species), but it only does one point at a time. For this project I'm working on, it would be super helpful to export the annotated points and each point have a coral species linked to it. Attached is an example of what I have in mind. If you have other suggestions/tools that you think would be helpful, please let me know! Thank you for taking this into consideration! :) 
![Screenshot 2024-11-01 144703](https://github.com/user-attachments/assets/649ad30c-f642-4760-b4fd-e45142e68330)
![Screenshot 2024-11-01 145356](https://github.com/user-attachments/assets/09528e23-426f-4bc5-a835-0d5bc53c8446)

**Comment by Jordan-Pierce** [comment]
Hi @esme3093 can you clarify: are you using / wanting to use CoralNet-Toolbox for this, or TagLab? I'm confused because you're showing my fork of TagLab, but posting in CoralNet-Toolbox.

If you do want to use CoralNet-Toolbox, then that's great! You already should have the ability to select existing annotations (using the SelectTool), by clicking on one (left-click), or holding down Ctrl + left-click to select multiple (and also, hold down Ctrl + left-click drag to select many within a rectangle). Once selected, you delete annotation(s) using Ctrl + Del key.

If this isn't working, you need to update doing this follow:
```bash
pip install "git+https://github.com/Jordan-Pierce/CoralNet-Toolbox.git" --upgrade
```

I would recommend doing this frequently, as I make changes almost daily.

**Comment by esme3093** [comment]
Hi Jordan,
Thanks for the quick response! I apologize, I am using Taglab for this, not the CoralNet-Toolbox. I just tried the Ctrl+ Del keys and it worked 😅 Thanks!

**Comment by esme3093** [comment]
In regard to linking points to a Region, do you suggest making another post under your Taglab fork? 

Again thanks so much!

**Comment by Jordan-Pierce** [comment]
I would do it under the official [TagLab](https://github.com/cnr-isti-vclab/TagLab) repo, as starting in the new year, any additional features I add will be there, not my fork (which, you're using). Slowly over time, the goal is to completely remove my fork, and only contribute to the official repo.

Regarding automated point annotations, TagLab currently uses CoralNet to do so, but the CoralNet-Toolbox (this repo), trains a model locally using your points / images, which you can use to classify new points in new images (see [this demo video](https://www.youtube.com/watch?v=1Etd_29v4uI)). The ability to transfer between TagLab and CoralNet-Toolbox right now is limited, and only import / exports TagLab polygon annotations, but not points, nor does it preserve Genet IDs (yet).

**Comment by esme3093** [comment]
Got it! Thanks for all the help! 🙌
