### ISSUE TITLE
Cycle through annotations associated with a label across images 

### ISSUE THREAD

**Issue by m-h-williams** [Jordan-Pierce/CoralNet-Toolbox#86]
### Description

Describe the feature (e.g., new functions/tutorials) you would like to propose.

- Currently, we are able to cycle through images and annotations using hotkeys. I propose adding the ability to select a label in the label window and cycle through associated annotations within the same image first and then across images.

Tell us what can be achieved with this new feature and what's the expected outcome.

This idea emerged as I was trying to locate a rare label within my dataset. I didn't see a way to directly find and navigate to the specific label annotation, instead I had to manually scroll through the images.
- This feature would allow users to focus on specific labels more efficiently.
-  It would streamline the process of reviewing annotations for consistency and accuracy by allowing users to navigate directly through all instances of a selected label.
-  By reducing the effort spent on searching, users can review and edit datasets more quickly,

I realize this is related to the cleaning patches feature we have discussed, but I think the suggested functionality would integrate into the current Toolbox workflow nicely.

**Comment by Jordan-Pierce** [comment]
@m-h-williams I like the idea of identifying the specific images that contain a label (I myself have dealt with this issue). However, instead of doing hot-keys to cycle through annotations with the desired label, I beefed up the search / filter capabilities. Hopefully with this, and the the ability to hide other annotations with the transparency slider, it will make finding your target annotations easier.

Major changes are:
- grouped the search / filter UI together 
- added another search bar for labels
- made both search bars dropdowns, auto-populated with image names, and annotation's short labels
- using AND logic, so filters by (image name AND label name)
- Shows the number of annotations in each image

The last feature needs an update, as it doesn't update the number in the table automatically as you create more / delete some annotations for the image. I need to think about how to best do this for annotations made / deleted manually and automatically.

![image](https://github.com/user-attachments/assets/93030306-4cdd-49d0-b0d9-98e4ec3bc9f2)

Let me know if this update (0.0.16) does what you need, or if it's still lacking.

**Comment by Jordan-Pierce** [comment]
Hey @m-h-williams I think I know a way it can happen:

- add a lock icon in the top-right part of the label window
- when clicked, sorts / filters images with annotations of the label currently selected (re filter / sort when label manually changed)
- with lock icon active, only allow cycling (left, right arrows) to the selected label

Is that right?

**Comment by Jordan-Pierce** [comment]
- press the "select" tool
- then press the label lock button

This allows you to stay on the same label and cycle through annotations with that label in the current image (combined with filtering, and adjusting all other labels to 0 transparency you should be able to find what you're looking for a lot easier)

Things to note:
- cycle left right with lock "locked" works fine
- if you select a machine predictions that matches the locked label, that's fine
- if you select a machine prediction / label that does not match locked label, that's fine (just keep cycling)
- If you change tools or do anything, lock will become unlocked (there's no good reason for this, I just assume with it locked, it might create other issues)
- I haven't tested it extensively, so let me know if you come across any bugs
- the image annotation count updates in real time, but the filtering does not (you need to select a new image, I might add a refresh button)


![image](https://github.com/user-attachments/assets/6ab62385-61e5-43b1-8c1d-eed15c20539d)

**Comment by Jordan-Pierce** [comment]
It just occurred to me that it might also to be useful such that you cannot select any annotations with a label that doesn't match what is currently locked. This would make it easier if you have a lot of annotations all in the same spot, and you want to select that specific locked label, but cannot because it's covered.

**Comment by Jordan-Pierce** [comment]
> It just occurred to me that it might also to be useful such that you cannot select any annotations with a label that doesn't match what is currently locked. This would make it easier if you have a lot of annotations all in the same spot, and you want to select that specific locked label, but cannot because it's covered.

Okay, this has been completed.

**Comment by m-h-williams** [comment]
@Jordan-Pierce This is fantastic! I can easily select a label, cycle through the annotations on one image, and then move to the next image to cycle through the annotations of the same label. Thank you so much for implementing this!

I’ll let you know if I come across any bugs as I continue to test it out. Thanks again!
